### ISSUE TITLE
Mac version?

### ISSUE THREAD

**Issue by justinfrench** [curiores/SerialAnalyzer#2]
This looks awesome! Would it be possible to get this working on Mac as well. The main serialport package seems to be compatible, is there anything platform specific?

**Comment by curiores** [comment]
Hi Justin, thanks for asking! No -- I built it to be cross-platform. I just haven't had a chance to get a service running to compile it on mac yet. I should be able to do that shortly.

**Comment by justinfrench** [comment]
Amazing, please let me know if I can help with testing or anything.

**Comment by sebassnu18** [comment]
Is there any update regarding this request? I am also interested in running in with macOS. Thanks!

**Comment by EvanBarnesCL** [comment]
I would also love to know if this works on Mac! I am trying to figure out the process needed to build from source, but I'm in over my head on that one so far. It seems like you need to install Node.js and the Yarn package manager, and then build it from the cloned repo? This is the exact application I need to fine tune a low pass filter for light sensors for a project I'm working on.

**Comment by EvanBarnesCL** [comment]
Hey there! I just wanted to report back to say that I figured out how to build the Mac version from the source code, and it works great! I tried to fork this repo, add the built Mac version, and then issue a PR, but the file size is too large for a standard repo. I tried to use git's LFS thing for large files, but I've never used that before, and somehow it now thinks that my repo that doesn't have any files in it is over the data limit. Anyway, I'm going to keep trying to figure out how to host the built Mac version for people, either as a fork, or possibly elsewhere. In the meantime, if anyone wants to build it themselves, it actually wasn't too hard, and I'd be happy to walk you through the steps I took. I had never used Node.js or Yarn electron before and I still got it done, so you can too! This application is well worth it. This is the best serial plotter I've ever used, and it's helping me design filters for sensors on a robotics project.

**Comment by curiores** [comment]
Thanks for doing that Evan and sorry I didn't respond -- I have out of touch with some of this work recently.

I actually have a mac now so I can pretty easily build the application on it and then upload the files to my site. Any issues I should know about that you had to debug during the build?

Thanks,
CR

**Comment by EvanBarnesCL** [comment]
Hey, no worries! You made an awesome free tool that's the best serial plotter I've ever seen as what seems like a passion project, I'm not expecting a super fast turn around on anything. The build went really smoothly and the application works great! The only issues I ran into were me not know what I was doing. This is a seriously awesome set of resources you've put out. I just used this and your Jupyter notebooks to build a low pass Butterworth filter for a project I'm working on, and it's the clearest resource I've found for someone entirely new to DSP.

**Comment by curiores** [comment]
I appreciate the kind words, Evan.

I compiled on MAC and, like you, I surprisingly did not run into build issues. Typically there would be at least one or two.

I've uploaded the version compiled on MAC (arm64), can you test it out for me? Then I can close this issue.

**Comment by EvanBarnesCL** [comment]
Sorry for the slow response! It's a hectic week. I just downloaded the file, but unfortunately, I get an error saying 'The application “Serial Analyzer.app” can’t be opened.' I tried to look into what might be causing this, and one idea I came across was that zipping an application can potentially strip it of execution settings. There was a proposed fix using the chmod command in the terminal, but I really don't know Mac well enough though to go messing with a command that could brick the whole filesystem on my work laptop. I did share my build of the application with my coworkers as a zip file, but none of them had tried to use it yet, and it turns out to have the same problem. When I built the application, it also generated a .dmg installer, so I wonder if sharing the installer instead of zipping the application might work. I just shared that with my coworkers too, and hopefully they'll try that out soon and I can let you know!

**Comment by EvanBarnesCL** [comment]
One of my coworkers just tried both the app and the dmg file, and neither worked unfortunately. The dmg file yielded an application that had an error saying the application was damaged and could not be opened. I'm so confused about why it would work fine when I built it on my computer, but not when shared with other people!

**Comment by curiores** [comment]
Thanks for the feedback, I'll review the electron app build settings this weekend and see if I can get it sorted. (might be some mac-specific settings that I haven't had to handle so far)

**Comment by curiores** [comment]
I've recompiled in a couple of different formats. I created the zip file through the build process rather than zipping it manually.

If you have time and want to try these, please let me know if they are working or what errors you are encountering. Right now I can't seem to find any specific issues as to why these might not be working.

**Comment by curiores** [comment]
Closing this for now since I've uploaded equivalent files for mac. Please let me know of any issues encountered.
